services:
  rest-api:
    image: rest-api:latest
    container_name: rest-api
    ports:
      - ${LOCAL_API_PORT:-80}:80
    environment:
      - AUTH_USER=${AUTH_USER:-user}
      - AUTH_PASS=${AUTH_PASS:-password}
